# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Markit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
