# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Markit', '0002_system_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=256)),
                ('symbol.csv', models.FileField(upload_to='')),
            ],
        ),
    ]
