# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Markit', '0003_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='symbol.csv',
        ),
        migrations.AddField(
            model_name='stock',
            name='file',
            field=models.FileField(default='tmp', upload_to='files/%Y/%m/%d'),
        ),
    ]
